const data = [
 {
   "nombre": "Instituto Nacional de Perinatologia",
   "tipo_centro": "Academico",
   "dir": "Calle Montes Urales 800, Miguel Hidalgo, Lomas Virreyes, 11000 Ciudad de Mexico, CDMX",
   "horario": "Las 24 horas",
   "dias": "Lunes a domingo",
   "lon": -99.2058139,
   "lat": 19.4231682,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Primeros auxilios, Alimento para mascotas",
   "entidades_que_apoya": "Juchitan",
   "entidad": "CDMX"
 },
 {
   "nombre": "Locatel",
   "tipo_centro": "Gobierno",
   "dir": "Heroes del 47 No. 113, San Mateo Churubusco, 04120 Coyoacan, CDMX",
   "horario": "9:00 - 18:00",
   "dias": "Lunes a domingo",
   "lon": -99.1499681,
   "lat": 19.3514956,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "CDMX"
 },
 {
   "nombre": "Restaurante Comixcal",
   "tipo_centro": "Ciudadano",
   "dir": "Dr. Atl 176, Sta Maria la Ribera, 06400 Ciudad de Mexico, CDMX",
   "horario": "14:30 - 22:00",
   "dias": "Lunes a domingo",
   "lon": -99.1563685,
   "lat": 19.4484336,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Ropa",
   "entidades_que_apoya": "Juchitan",
   "entidad": "CDMX"
 },
 {
   "nombre": "PRI Nacional",
   "tipo_centro": "Ciudadano",
   "dir": "Avenida Insurgentes Norte 59, Buenavista, 06359 Cuauhtemoc, CDMX, Mexico",
   "horario": "",
   "dias": "",
   "lon": -99.154322,
   "lat": 19.441615,
   "tipo": "Alimentos, Higiene Personal, Limpieza del Hogar",
   "entidades_que_apoya": "12 entidades federativas afectadas",
   "entidad": "CDMX"
 },
 {
   "nombre": "Instancia Coordinadora Nacional de la Seccion XXII de Oaxaca",
   "tipo_centro": "Ciudadano",
   "dir": "Av. Coyoacan 939, Col del Valle Centro, 03100 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "",
   "lon": -99.1686104,
   "lat": 19.381953,
   "tipo": "Medicamentos, Material de de curacion",
   "entidades_que_apoya": "Istmo",
   "entidad": "CDMX"
 },
 {
   "nombre": "Centro Cultural Macario Matus",
   "tipo_centro": "Ciudadano",
   "dir": "Almacenes 74, Cuauhtemoc, 06900 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "",
   "lon": -99.1359304,
   "lat": 19.4504745,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar",
   "entidades_que_apoya": "Juchitan",
   "entidad": "CDMX"
 },
 {
   "nombre": "Zocalo",
   "tipo_centro": "Gobierno",
   "dir": "Plaza de la Constitucion S/N, Centro, Cuauhtemoc, 06010 Ciudad de Mexico, CDMX, Mexico",
   "horario": "9:00 - 18:00",
   "dias": "Lunes a Domingo",
   "lon": -99.1332049,
   "lat": 19.4326018,
   "tipo": "Articulos de primera necesidad, Higiene personal, Limpieza del hogar",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "CDMX"
 },
 {
   "nombre": "Sandoval Contadores Publicos",
   "tipo_centro": "Ciudadano",
   "dir": "Lago Wetter 134, Cuauhtemoc Pensil, 11490 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "",
   "lon": -99.1937932,
   "lat": 19.4449117,
   "tipo": "",
   "entidades_que_apoya": "Istmo",
   "entidad": "CDMX"
 },
 {
   "nombre": "ENAH",
   "tipo_centro": "Academico",
   "dir": "Periferico Sur y Zapote s/n. Colonia Isidro Fabela, Tlalpan, Isidro Fabela, 14030 Ciudad de Mexico, CDMX",
   "horario": "7:00 - 15:00",
   "dias": "",
   "lon": -99.1798404,
   "lat": 19.3023275,
   "tipo": "",
   "entidades_que_apoya": "Pueblos huaves, Juchitan",
   "entidad": "CDMX"
 },
 {
   "nombre": "UNAM - Estadio Olimpico Universtario",
   "tipo_centro": "Academico",
   "dir": "Universidad Nacional Autonoma de Mexico C.U., Av de los Insurgentes Sur S/N, Cd. Universitaria, 04510 Ciudad de Mexico, CDMX, Mexico",
   "horario": "9:00 - 17:00",
   "dias": "Sabado",
   "lon": -99.1921777,
   "lat": 19.3319125,
   "tipo": "Alimentos, Productos de Higiene Personal, Limpieza del hogar",
   "entidades_que_apoya": "",
   "entidad": "CDMX"
 },
 {
   "nombre": "DIF Nacional",
   "tipo_centro": "Gobierno",
   "dir": "Gral. Emiliano Zapata 340, Sta Cruz Atoyac, 03310 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "",
   "lon": -99.162057,
   "lat": 19.3695354,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Primeros auxilios, Medicamentos, Alimentos para bebe",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "CDMX"
 },
 {
   "nombre": "DIF - Almacenes Generales",
   "tipo_centro": "Gobierno",
   "dir": "Av. Mexico Coyoacan 278, Sta Cruz Atoyac, 03310 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "",
   "lon": -99.1632828,
   "lat": 19.3661932,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Primeros auxilios, Medicamentos, Alimentos para bebe",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "CDMX"
 },
 {
   "nombre": "DIF - Casa Hogar para Ninas Graciela Zubiran",
   "tipo_centro": "Gobierno",
   "dir": "Avenida de los Insurgentes Sur 3700B, Insurgentes Cuicuilco, 04530 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "",
   "lon": -99.1862268,
   "lat": 19.3075602,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Primeros auxilios, Medicamentos, Alimentos para bebe",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "CDMX"
 },
 {
   "nombre": "DIF - Direccion General de Integracion Social",
   "tipo_centro": "Gobierno",
   "dir": "Av. Insurgentes Sur 3700B, Insurgentes Cuicuilco, 04530 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "",
   "lon": -99.1864679,
   "lat": 19.3078736,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Primeros auxilios, Medicamentos, Alimentos para bebe",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "CDMX"
 },
 {
   "nombre": "Seminario de Cultura Mexicana",
   "tipo_centro": "Ciudadano",
   "dir": "Av. Pdte. Masaryk 526, Polanco, Polanco II Secc, 11550 Ciudad de Mexico, CDMX",
   "horario": "9:00 - 19:00",
   "dias": "",
   "lon": -99.2049472,
   "lat": 19.4320662,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Otros",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "CDMX"
 },
 {
   "nombre": "Representacion de Oaxaca en la CDMX",
   "tipo_centro": "Gobierno",
   "dir": "Shakespeare 68, Anzures, 11590 Ciudad de Mexico, CDMX\n",
   "horario": "",
   "dias": "",
   "lon": -99.1772563,
   "lat": 19.4283907,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Otros",
   "entidades_que_apoya": "Oaxaca",
   "entidad": "CDMX"
 },
 {
   "nombre": "PALECH, Pacto de America Latina por la Educacion con Calidad Humana",
   "tipo_centro": "Ciudadano",
   "dir": "Guanabana 201 Int. C, Nueva Santa Maria, 02800 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "",
   "lon": -99.1682402,
   "lat": 19.4655262,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Primeros auxilios, Medicamentos, Alimentos para bebe",
   "entidades_que_apoya": "Juchitan, Oaxaca",
   "entidad": "CDMX"
 },
 {
   "nombre": "Zoologico Los Coyotes",
   "tipo_centro": "Ciudadano",
   "dir": "Av. Heroica Escuela Naval Militar S/N, Coyoacan, Ex Ejido San Pablo Tepetlapa, 04900 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "A partir del domingo",
   "lon": -99.1246561,
   "lat": 19.3187726,
   "tipo": "",
   "entidades_que_apoya": "",
   "entidad": "CDMX"
 },
 {
   "nombre": "Delegacion Benito Juarez",
   "tipo_centro": "Gobierno",
   "dir": "Avenida Cuauhtemoc 1240, Sta Cruz Atoyac, 03310 Ciudad de Mexico, CDMX",
   "horario": "10:00 - 18:00",
   "dias": "",
   "lon": -99.1608446,
   "lat": 19.3719192,
   "tipo": "No perecederos, Toallas femeninas, Higiene Personal, Otros",
   "entidades_que_apoya": "",
   "entidad": "CDMX"
 },
 {
   "nombre": "Ensena por Mexico",
   "tipo_centro": "Ciudadano",
   "dir": "Calle Hamburgo 14, Int. PB, Col. Juarez, Del. Cuauhtemoc, Ciudad de Mexico",
   "horario": "09:00 - 18:00",
   "dias": "Lunes a viernes",
   "lon": -99.1608421,
   "lat": 19.4289758,
   "tipo": "Agua embotellada, alimentos enlatados, leche en polvo, botiquin de primeros auxilios, higiene personal.",
   "entidades_que_apoya": "",
   "entidad": "CDMX"
 },
 {
   "nombre": "Casa de Atencion Ciudadana Laura Plascencia",
   "tipo_centro": "Ciudadano",
   "dir": "Nicolas Bravo 31, Tonala Centro, 45400 Tonala, Jal",
   "horario": "",
   "dias": "",
   "lon": -103.245317,
   "lat": 20.6252797,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Otros",
   "entidades_que_apoya": "Istmo de Tehuantepec",
   "entidad": "Jalisco"
 },
 {
   "nombre": "Arquidiocesis Antequera Oaxaca",
   "tipo_centro": "Religioso",
   "dir": "Calle Macedonio Alcala 801, RUTA INDEPENDENCIA, Centro, 68000 Oaxaca, Oax.\n",
   "horario": "10:00 - 14:00, 17:00 - 19:00",
   "dias": "",
   "lon": -96.7233352,
   "lat": 17.0690643,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar",
   "entidades_que_apoya": "",
   "entidad": "Oaxaca"
 },
 {
   "nombre": "DIF Estatal - Gimnasio Flores Magon",
   "tipo_centro": "Gobierno",
   "dir": "Centro, 68000 Oaxaca",
   "horario": "",
   "dias": "",
   "lon": -96.7253164,
   "lat": 17.0637447,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar",
   "entidades_que_apoya": "",
   "entidad": "Oaxaca"
 },
 {
   "nombre": "Cruz Roja Tuxtla",
   "tipo_centro": "Cruz Roja",
   "dir": "Av. 5A. Norte Poniente 1480, Covandonga, Tuxtla Gutierrez, Chis., Mexico",
   "horario": "9:00 - 19:00",
   "dias": "",
   "lon": -93.1327293,
   "lat": 16.7611035,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Otros",
   "entidades_que_apoya": "Chiapas",
   "entidad": "Chiapas"
 },
 {
   "nombre": "Tecnologico de Monterrey Chiapas",
   "tipo_centro": "Academico",
   "dir": "DAE y Plaza Prepa- Carretera Tapanatepec- Tuxtla Gutierrez Km 149+746, Juan Crispin, 29020 Tuxtla Gutierrez, Chis.",
   "horario": "",
   "dias": "",
   "lon": -93.2030251,
   "lat": 16.765097,
   "tipo": "Alimentos no perecederos, Higiene personal, Limpieza general.",
   "entidades_que_apoya": "",
   "entidad": "Chiapas"
 },
 {
   "nombre": "La Purisima Cocina Oaxaquena",
   "tipo_centro": "Ciudadano",
   "dir": "Calle 25 Sur B 905, La Paz, 72160 Puebla, Pue.",
   "horario": "",
   "dias": "",
   "lon": -93.110086,
   "lat": 16.770447,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Cobijas",
   "entidades_que_apoya": "Istmo",
   "entidad": "Puebla"
 },
 {
   "nombre": "Zocalo de la Ciudad de Puebla",
   "tipo_centro": "Gobierno",
   "dir": "Juan de Palafox y Mendoza, Centro, 72000 Puebla, Pue.",
   "horario": "10:00 - 16:00",
   "dias": "",
   "lon": -98.2197061,
   "lat": 19.050877,
   "tipo": "",
   "entidades_que_apoya": "",
   "entidad": "Puebla"
 },
 {
   "nombre": "UPAEP",
   "tipo_centro": "Academico",
   "dir": "Calle 21 Sur 1103, Barrio de Santiago, 72410 Puebla, Pue.",
   "horario": "L a S 9:00 - 20:00, D 10:00 - 14:00",
   "dias": "Lunes a domingo",
   "lon": -98.195645,
   "lat": 19.0429188,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Cobijas",
   "entidades_que_apoya": "Oaxaca",
   "entidad": "Puebla"
 },
 {
   "nombre": "DIF Metepec",
   "tipo_centro": "Gobierno",
   "dir": "Av Manuel J. Clouthier No.70, Izcalli Cuauhtemoc V, 52176 Metepec, Mex.",
   "horario": "8:00 - 16:00",
   "dias": "Lunes a viernes",
   "lon": -98.2160623,
   "lat": 19.0480531,
   "tipo": "No perecederos, Higiene Personal, Agua embotellada",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "EdoMex"
 },
 {
   "nombre": "Explanada Norte, Estadio BBVA Bancomer",
   "tipo_centro": "Ciudadano",
   "dir": "Pablo Livas 2011, La Pastora, 67140 Guadalupe, N.L.",
   "horario": "",
   "dias": "A partir de las 17:00 del sabado 9 de septiembre",
   "lon": -99.5963832,
   "lat": 19.2695055,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Primeros auxilios, Medicamentos, Alimentos para bebe, Abrelatas, Bolsas de basura, Linternas y baterias",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "NL"
 },
 {
   "nombre": "Oficinas DIF Nuevo Leon ",
   "tipo_centro": "Gobierno",
   "dir": "Av. Morones Prieto 600 Ote., Col. Independencia, Monterrey, N.L.",
   "horario": "08:00 - 17:00",
   "dias": "",
   "lon": -100.2445578,
   "lat": 25.6679986,
   "tipo": "Alimentos (agua no), Higiene personal, Limpieza del hogar, Cobijas, Colchonetas.",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "NL"
 },
 {
   "nombre": "Universidad de Guadalajara en Coordinacion de Extension o en Servicios Medicos Integrales ",
   "tipo_centro": "Academico",
   "dir": "Periferico Norte N° 799, Nucleo Universitario Los Belenes, 45100 Zapopan, Jal.",
   "horario": "08:00 - 17:00",
   "dias": "",
   "lon": -103.3808525,
   "lat": 20.7407607,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Cobijas, Ropa",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "Jalisco"
 },
 {
   "nombre": "Presidencia Municipal Zapopan",
   "tipo_centro": "Gobierno",
   "dir": "Avenida Hidalgo 151, Zapopan, 45100 Zapopan, Jal.",
   "horario": "9:00 - 16:00",
   "dias": "",
   "lon": -103.3898239,
   "lat": 20.7216089,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Cobijas",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "Jalisco"
 },
 {
   "nombre": "DIF Zapopan",
   "tipo_centro": "Gobierno",
   "dir": "Av. Laureles 1151, Unidad Fovissste, 45149 Zapopan, Jal.",
   "horario": "9:00 - 15:00",
   "dias": "",
   "lon": -103.403356,
   "lat": 20.7379616,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Cobijas",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "Jalisco"
 },
 {
   "nombre": "DIF Playa del Carmen - Palapa de Usos Multiples",
   "tipo_centro": "Gobierno",
   "dir": "Calle 8 Nte, Gonzalo Guerrero, 77720 Playa del Carmen, Q.R.",
   "horario": "9:00 - 17:00",
   "dias": "Lunes a domingo",
   "lon": -87.076454,
   "lat": 20.6281345,
   "tipo": "Alimentos y agua, Higiene personal, Limpieza del hogar, Cobijas, Ropa y zapatos",
   "entidades_que_apoya": "Oaxaca, Chiapas",
   "entidad": "Quintana Roo"
 },
 {
   "nombre": "Cruz Roja Mexicana - Sede Nacional",
   "tipo_centro": "Cruz Roja",
   "dir": "uan Luis Vives 200, Polanco I Seccion, Polanco I Secc, 11510 Miguel Hidalgo, CDMX",
   "horario": "8:00 - 20:00",
   "dias": "Lunes a domingo",
   "lon": -99.2111772,
   "lat": 19.4378337,
   "tipo": "Atun, sardinas, frijoles, arroz, lenteja, sopa de pasta, chiles en lata, consome de pollo en polvo, verduras en lata, sal, mayonesa, aceite, cafe soluble, azucar, mermelada, chocolate en polvo, galletas, abrelatas",
   "entidades_que_apoya": "",
   "entidad": "CDMX"
 },
 {
   "nombre": "Cruz Roja Mexicana - Delegacion Estado de Mexico",
   "tipo_centro": "Cruz Roja",
   "dir": "Paseo Santa Elena 72, Fraccionamiento Santa Elena, 52100 San Mateo Atenco, Mex",
   "horario": "8:00 - 20:00",
   "dias": "Lunes a domingo",
   "lon": -99.54272,
   "lat": 19.2832777,
   "tipo": "Atun, sardinas, frijoles, arroz, lenteja, sopa de pasta, chiles en lata, consome de pollo en polvo, verduras en lata, sal, mayonesa, aceite, cafe soluble, azucar, mermelada, chocolate en polvo, galletas, abrelatas",
   "entidades_que_apoya": "",
   "entidad": "EdoMex"
 },
 {
   "nombre": "Cruz Roja Mexicana - Delegacion Oaxaca",
   "tipo_centro": "Cruz Roja",
   "dir": "Armenta y Lopez No. 700 Colonia Centro. CP: 68000 Oaxaca, Oaxaca.",
   "horario": "8:00 - 20:00",
   "dias": "Lunes a domingo",
   "lon": -96.7269703,
   "lat": 17.0559768,
   "tipo": "Atun, sardinas, frijoles, arroz, lenteja, sopa de pasta, chiles en lata, consome de pollo en polvo, verduras en lata, sal, mayonesa, aceite, cafe soluble, azucar, mermelada, chocolate en polvo, galletas, abrelatas",
   "entidades_que_apoya": "",
   "entidad": "Oaxaca"
 },
 {
   "nombre": "Cruz Roja Mexicana - Delegacion Chiapas",
   "tipo_centro": "Cruz Roja",
   "dir": "Libramiento Nte. Ote. 451, Albania Baja, 29010 Tuxtla Gutierrez, Chis.",
   "horario": "8:00 - 20:00",
   "dias": "Lunes a domingo",
   "lon": -93.1122747,
   "lat": 16.7704521,
   "tipo": "Atun, sardinas, frijoles, arroz, lenteja, sopa de pasta, chiles en lata, consome de pollo en polvo, verduras en lata, sal, mayonesa, aceite, cafe soluble, azucar, mermelada, chocolate en polvo, galletas, abrelatas",
   "entidades_que_apoya": "",
   "entidad": "Chiapas"
 },
 {
   "nombre": "Cruz Roja Mexicana - Delegacion Tabasco",
   "tipo_centro": "Cruz Roja",
   "dir": "Av. Paseo Tabasco No. 613, Colonia Jesus Garcia, 86040, Villahermosa, Tabasco.",
   "horario": "8:00 - 20:00",
   "dias": "Lunes a domingo",
   "lon": -92.9526902,
   "lat": 17.9934085,
   "tipo": "Atun, sardinas, frijoles, arroz, lenteja, sopa de pasta, chiles en lata, consome de pollo en polvo, verduras en lata, sal, mayonesa, aceite, cafe soluble, azucar, mermelada, chocolate en polvo, galletas, abrelatas",
   "entidades_que_apoya": "",
   "entidad": "Tabasco"
 },
 {
   "nombre": "Campo Marte",
   "tipo_centro": "Gobierno",
   "dir": "Avenida Paseo de La Reforma, Miguel Hidalgo, San Miguel Chapultepec, 11850 Ciudad de Mexico, CDMX",
   "horario": "",
   "dias": "Lunes a domingo",
   "lon": -99.19366,
   "lat": 19.421994,
   "tipo": "Atun, sardinas, frijoles, arroz, lenteja, sopa de pasta, chiles en lata, consome de pollo en polvo, verduras en lata, sal, mayonesa, aceite, cafe soluble, azucar, mermelada, chocolate en polvo, galletas, abrelatas",
   "entidades_que_apoya": "",
   "entidad": "CDMX"
 }
]

export default data;
